<a href="https://colab.research.google.com/github/Noobs-in-Devhack/AI---ML-/blob/main/L%20-%20User_Based_Collaborative_Filtering.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import warnings
warnings.filterwarnings('ignore')

In [ ]:
df_user = pd.read_csv("https://github.com/ammishra08/MachineLearning/raw/master/Datasets/BX-Users.csv", encoding = "latin-1")
df_user.head()

user_id                            Location   Age
0       1                  nyc, new york, usa   NaN
1       2           stockton, california, usa  18.0
2       3     moscow, yukon territory, russia   NaN
3       4           porto, v.n.gaia, portugal  17.0
4       5  farnborough, hants, united kingdom   NaN

In [ ]:
df_books = pd.read_csv("https://github.com/ammishra08/MachineLearning/raw/master/Datasets/BX-Books.csv", encoding='latin-1')
df_books.head()

isbn                                         book_title  \
0  195153448                                Classical Mythology   
1    2005018                                       Clara Callan   
2   60973129                               Decision in Normandy   
3  374157065  Flu: The Story of the Great Influenza Pandemic...   
4  393045218                             The Mummies of Urumchi   

            book_author year_of_publication                   publisher  
0    Mark P. O. Morford                2002     Oxford University Press  
1  Richard Bruce Wright                2001       HarperFlamingo Canada  
2          Carlo D'Este                1991             HarperPerennial  
3      Gina Bari Kolata                1999        Farrar Straus Giroux  
4       E. J. W. Barber                1999  W. W. Norton &amp; Company

In [ ]:
df_ratings = pd.read_csv("https://github.com/ammishra08/MachineLearning/raw/master/Datasets/BX-Book-Ratings.csv",
                         encoding = 'latin-1', nrows = 10000)

In [ ]:
df_ratings.head()

user_id        isbn  rating
0   276725  034545104X       0
1   276726   155061224       5
2   276727   446520802       0
3   276729  052165615X       3
4   276729   521795028       6

In [ ]:
df_ratings.describe()

user_id        rating
count   10000.000000  10000.000000
mean   265844.379600      1.974700
std     56937.189618      3.424884
min         2.000000      0.000000
25%    277478.000000      0.000000
50%    278418.000000      0.000000
75%    278418.000000      4.000000
max    278854.000000     10.000000

In [ ]:
# merge = inner join between two dataframes
df = pd.merge(df_ratings, df_books, on = 'isbn')
df.head()

user_id        isbn  rating            book_title      book_author  \
0   276725  034545104X       0  Flesh Tones: A Novel       M. J. Rose   
1   276726   155061224       5      Rites of Passage       Judith Rae   
2   276727   446520802       0          The Notebook  Nicholas Sparks   
3   278418   446520802       0          The Notebook  Nicholas Sparks   
4   276729  052165615X       3        Help!: Level 1    Philip Prowse   

  year_of_publication                   publisher  
0                2002            Ballantine Books  
1                2001                      Heinle  
2                1996                Warner Books  
3                1996                Warner Books  
4                1999  Cambridge University Press

In [ ]:
n_users = df.user_id.nunique()
n_books = df.isbn.nunique()
print("Num of Users: ", n_users)
print("Num of Books: ", n_books)

Num of Users:  828
Num of Books:  8051


##### Convert ISBN to numeric index in order format.

In [ ]:
isbn_list = df.isbn.unique()
def get_isbn_numeric_index(isbn):
  itemindex = np.where(isbn_list == isbn)
  return itemindex[0][0]

In [ ]:
userid_list = df.user_id.unique()
print(" Length of user_id List:", len(userid_list))
def get_userid_numeric_index(user_id):
  itemindex = np.where(userid_list == user_id)
  return itemindex[0][0]

 Length of user_id List: 828


##### Convert ISBN & User ID to an ordered list format i.e. from 0, 1, 2, ... n-1

In [ ]:
df['user_id_order'] = df['user_id'].apply(get_userid_numeric_index)
df['isbn_id'] = df['isbn'].apply(get_isbn_numeric_index)

In [ ]:
df

user_id        isbn  rating                book_title  \
0      276725  034545104X       0      Flesh Tones: A Novel   
1      276726   155061224       5          Rites of Passage   
2      276727   446520802       0              The Notebook   
3      278418   446520802       0              The Notebook   
4      276729  052165615X       3            Help!: Level 1   
...       ...         ...     ...                       ...   
8696      243   385720106       7        A Map of the World   
8697      243   425092917       0    The Accidental Tourist   
8698      243   425098834       0     If Morning Ever Comes   
8699      243   425163407       9        Unnatural Exposure   
8700      243   425164403       0  Only Love (Magical Love)   

                    book_author year_of_publication  \
0                    M. J. Rose                2002   
1                    Judith Rae                2001   
2               Nicholas Sparks                1996   
3               Nicholas Sparks                1996   
4                 Philip Prowse                1999   
...                         ...                 ...   
8696              Jane Hamilton                1999   
8697                 Anne Tyler                1994   
8698                 Anne Tyler                1983   
8699  Patricia Daniels Cornwell                1998   
8700                Erich Segal                1998   

                       publisher  user_id_order  isbn_id  
0               Ballantine Books              0        0  
1                         Heinle              1        1  
2                   Warner Books              2        2  
3                   Warner Books              3        2  
4     Cambridge University Press              4        3  
...                          ...            ...      ...  
8696      Anchor Books/Doubleday             96     8046  
8697    Berkley Publishing Group             96     8047  
8698    Berkley Publishing Group             96     8048  
8699    Berkley Publishing Group             96     8049  
8700    Berkley Publishing Group             96     8050  

[8701 rows x 9 columns]

In [ ]:
new_col_order = ['user_id_order', 'isbn_id', 'rating', 'book_title', 'book_author','year_of_publication','publisher','isbn','user_id']
df = df.reindex(columns = new_col_order)
df.head()

user_id_order  isbn_id  rating            book_title      book_author  \
0              0        0       0  Flesh Tones: A Novel       M. J. Rose   
1              1        1       5      Rites of Passage       Judith Rae   
2              2        2       0          The Notebook  Nicholas Sparks   
3              3        2       0          The Notebook  Nicholas Sparks   
4              4        3       3        Help!: Level 1    Philip Prowse   

  year_of_publication                   publisher        isbn  user_id  
0                2002            Ballantine Books  034545104X   276725  
1                2001                      Heinle   155061224   276726  
2                1996                Warner Books   446520802   276727  
3                1996                Warner Books   446520802   278418  
4                1999  Cambridge University Press  052165615X   276729

#### Split into train & Test

In [ ]:
from sklearn.model_selection import train_test_split
train_data, test_data = train_test_split(df, test_size = 0.3)

In [ ]:
train_data_matrix = np.zeros((n_users, n_books))
for line in train_data.itertuples():
    train_data_matrix[line[1]-1, line[2]-1] = line[3]

In [ ]:
train_data_matrix

array([[5., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [ ]:
test_data_matrix = np.zeros((n_users, n_books))
for line in test_data.itertuples():
    test_data_matrix[line[1]-1, line[2]-1] = line[3]

In [ ]:
test_data_matrix

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [ ]:
pd.DataFrame(train_data_matrix)

0     1     2     3     4     5     6     7     8     9     ...  8041  \
0     5.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  ...   0.0   
1     0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  ...   0.0   
2     0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  ...   0.0   
3     0.0   0.0   0.0   6.0   0.0   0.0   0.0   0.0   0.0   0.0  ...   0.0   
4     0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  ...   0.0   
..    ...   ...   ...   ...   ...   ...   ...   ...   ...   ...  ...   ...   
823   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  ...   0.0   
824   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  ...   0.0   
825   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  ...   0.0   
826   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  ...   0.0   
827   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  ...   0.0   

     8042  8043  8044  8045  8046  8047  8048  8049  8050  
0     0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  
1     0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  
2     0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  
3     0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  
4     0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  
..    ...   ...   ...   ...   ...   ...   ...   ...   ...  
823   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  
824   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  
825   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  
826   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  
827   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  

[828 rows x 8051 columns]

#### Pairwise Similarity

In [ ]:
from sklearn.metrics.pairwise import pairwise_distances
user_similarity = pairwise_distances(train_data_matrix, metric = 'cosine')
item_similarity = pairwise_distances(train_data_matrix.T, metric = 'cosine')

In [ ]:
pd.DataFrame(user_similarity)

0    1    2    3    4    5    6    7    8    9    ...  818  819  820  \
0    0.0  1.0  1.0  1.0  1.0  1.0  1.0  1.0  1.0  1.0  ...  1.0  1.0  1.0   
1    1.0  0.0  1.0  1.0  1.0  1.0  1.0  1.0  1.0  1.0  ...  1.0  1.0  1.0   
2    1.0  1.0  0.0  1.0  1.0  1.0  1.0  1.0  1.0  1.0  ...  1.0  1.0  1.0   
3    1.0  1.0  1.0  0.0  1.0  1.0  1.0  1.0  1.0  1.0  ...  1.0  1.0  1.0   
4    1.0  1.0  1.0  1.0  0.0  1.0  1.0  1.0  1.0  1.0  ...  1.0  1.0  1.0   
..   ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...   
823  1.0  1.0  1.0  1.0  1.0  1.0  1.0  1.0  1.0  1.0  ...  1.0  1.0  1.0   
824  1.0  1.0  1.0  1.0  1.0  1.0  1.0  1.0  1.0  1.0  ...  1.0  1.0  1.0   
825  1.0  1.0  1.0  1.0  1.0  1.0  1.0  1.0  1.0  1.0  ...  1.0  1.0  1.0   
826  1.0  1.0  1.0  1.0  1.0  1.0  1.0  1.0  1.0  1.0  ...  1.0  1.0  1.0   
827  1.0  1.0  1.0  1.0  1.0  1.0  1.0  1.0  1.0  1.0  ...  1.0  1.0  1.0   

     821  822  823  824  825  826  827  
0    1.0  1.0  1.0  1.0  1.0  1.0  1.0  
1    1.0  1.0  1.0  1.0  1.0  1.0  1.0  
2    1.0  1.0  1.0  1.0  1.0  1.0  1.0  
3    1.0  1.0  1.0  1.0  1.0  1.0  1.0  
4    1.0  1.0  1.0  1.0  1.0  1.0  1.0  
..   ...  ...  ...  ...  ...  ...  ...  
823  1.0  1.0  0.0  1.0  1.0  1.0  1.0  
824  1.0  1.0  1.0  0.0  1.0  1.0  1.0  
825  1.0  1.0  1.0  1.0  0.0  1.0  1.0  
826  1.0  1.0  1.0  1.0  1.0  0.0  1.0  
827  1.0  1.0  1.0  1.0  1.0  1.0  0.0  

[828 rows x 828 columns]

#### Expected Ratings

In [ ]:
def predict(ratings, similarity, type='user'):
    if type == 'user':
        mean_user_rating = ratings.mean(axis=1)
        #You use np.newaxis so that mean_user_rating has same format as ratings
        ratings_diff = (ratings - mean_user_rating[:, np.newaxis])
        pred = mean_user_rating[:, np.newaxis] + similarity.dot(ratings_diff) / np.array([np.abs(similarity).sum(axis=1)]).T
    elif type == 'item':
        pred = ratings.dot(similarity) / np.array([np.abs(similarity).sum(axis=1)])
    return pred

In [ ]:
item_prediction = predict(train_data_matrix, item_similarity, type = "item")
user_prediction = predict(train_data_matrix, user_similarity, type = "user")

In [ ]:
item_prediction

array([[0.        , 0.00062112, 0.00062112, ..., 0.00062151, 0.00062112,
        0.00062112],
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.05279503, 0.05279503, 0.05279503, ..., 0.05282846, 0.05279503,
        0.05279503],
       ...,
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ]])

In [ ]:
pd.DataFrame(item_prediction)[0].max()

0.10869565217391304

In [ ]:
# Next 5 Recommended Books
np.where(pd.DataFrame(item_prediction).loc[78] == pd.DataFrame(item_prediction).loc[78].max())[0][:5]

array([ 667,  943, 1125, 1132, 1144])