<a href="https://colab.research.google.com/github/Noobs-in-Devhack/AI---ML-/blob/main/Numpy_%26_Pandas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# Numerical Python - N-D arrays, matrix, mathematical and statistical computation & linear algebric equation
import numpy as np

In [ ]:
arr_1 = np.array([10, 20, 30, 40, 50, 60, 70, 80])     # 1-D Array
print(arr_1)

[10 20 30 40 50 60 70 80]


In [ ]:
type(arr_1)

numpy.ndarray

In [ ]:
print(arr_1.shape)      # returns shape of numpy array - num of rows, num of columns
print(arr_1.ndim)       # num of dimentionality
print(arr_1.size)       # num of elements in an array.

(8,)
1
8


#### Types of Arrays - 2D, 3-D

In [ ]:
# 2D Array - Matrix
arr_2 = np.array([[10, 20, 30, 40, 50, 60, 70],
                  [21, 22, 23, 25, 27, 28, 32],
                  [31, 35, 36, 38, 43, 47, 51]])
print(arr_2)

[[10 20 30 40 50 60 70]
 [21 22 23 25 27 28 32]
 [31 35 36 38 43 47 51]]


In [ ]:
print(arr_2.shape)      # returns shape of numpy array - num of rows, num of columns
print(arr_2.ndim)       # num of dimentionality
print(arr_2.size)       # num of elements in an array

(3, 7)
2
21


In [ ]:
# 3D Array - Collection of Matrices
arr_3 = np.array([[[10, 20, 30, 40, 50, 60, 70],
                  [21, 22, 23, 25, 27, 28, 32],
                  [31, 35, 36, 38, 43, 47, 51]],

                 [[11, 21, 31, 40, 52, 63, 75],
                  [21, 22, 23, 29, 27, 28, 32],
                  [31, 35, 38, 38, 43, 47, 51]]])
print(arr_3)

[[[10 20 30 40 50 60 70]
  [21 22 23 25 27 28 32]
  [31 35 36 38 43 47 51]]

 [[11 21 31 40 52 63 75]
  [21 22 23 29 27 28 32]
  [31 35 38 38 43 47 51]]]


In [ ]:
print(arr_3.shape)      # returns shape of numpy array - num of rows, num of columns
print(arr_3.ndim)       # num of dimentionality
print(arr_3.size)       # num of elements in an array

(2, 3, 7)
3
42


#### Numpy Methods

In [ ]:
# start value = 1, end value = 50
arr_4 = np.arange(1, 51)
arr_4

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50])

In [ ]:
arr_6 = np.arange(1, 51).reshape(2, 5, 5)
print(arr_6)

[[[ 1  2  3  4  5]
  [ 6  7  8  9 10]
  [11 12 13 14 15]
  [16 17 18 19 20]
  [21 22 23 24 25]]

 [[26 27 28 29 30]
  [31 32 33 34 35]
  [36 37 38 39 40]
  [41 42 43 44 45]
  [46 47 48 49 50]]]


In [ ]:
arr_6 = np.arange(1, 51).reshape(10,5)
print(arr_6)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]
 [26 27 28 29 30]
 [31 32 33 34 35]
 [36 37 38 39 40]
 [41 42 43 44 45]
 [46 47 48 49 50]]


In [ ]:
# Create an array using np.ones() matrix
np.ones([6,6])        # shape (6 = rows, 6 = columns)

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

In [ ]:
# Create an array using np.zeros() matrix, zero matrx
np.zeros([7, 7])        # shape (7 = rows, 7 = columns)

array([[0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.]])

In [ ]:
np.identity(6)

array([[1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1.]])

In [ ]:
arr_6 = np.arange(1, 51).reshape(10,5)
print(arr_6)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]
 [26 27 28 29 30]
 [31 32 33 34 35]
 [36 37 38 39 40]
 [41 42 43 44 45]
 [46 47 48 49 50]]


In [ ]:
np.where(arr_6 == 23)

(array([4]), array([2]))

In [ ]:
np.where(arr_6 >= 40)

(array([7, 8, 8, 8, 8, 8, 9, 9, 9, 9, 9]),
 array([4, 0, 1, 2, 3, 4, 0, 1, 2, 3, 4]))

#### Mathemtical & statistical methods

In [ ]:
arr_7 = np.arange(1, 51).reshape(10,5)
print(arr_7)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]
 [26 27 28 29 30]
 [31 32 33 34 35]
 [36 37 38 39 40]
 [41 42 43 44 45]
 [46 47 48 49 50]]


In [ ]:
arr_7.sum()      # sum of all elements

1275

In [ ]:
arr_7.sum(axis = 0)     # rowwise summarion , axis = 0 (rowwise)

array([235, 245, 255, 265, 275])

In [ ]:
arr_7.sum(axis = 1)     # columnwise summation,

array([ 15,  40,  65,  90, 115, 140, 165, 190, 215, 240])

In [ ]:
print(arr_7.min())
print(arr_7.max())

1
50


In [ ]:
arr_7 + 2       # addition of 2 to each element

array([[ 3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22],
       [23, 24, 25, 26, 27],
       [28, 29, 30, 31, 32],
       [33, 34, 35, 36, 37],
       [38, 39, 40, 41, 42],
       [43, 44, 45, 46, 47],
       [48, 49, 50, 51, 52]])

In [ ]:
arr_7 - 3       # subtraction of 2 to each element

array([[-2, -1,  0,  1,  2],
       [ 3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22],
       [23, 24, 25, 26, 27],
       [28, 29, 30, 31, 32],
       [33, 34, 35, 36, 37],
       [38, 39, 40, 41, 42],
       [43, 44, 45, 46, 47]])

In [ ]:
arr_8 = [[10, 12, 13, 16],
         [21, 19, 11, 15]]
# square root
print(np.sqrt(arr_8))

# logarithmic & exponential
print(np.log(arr_8))

print(np.exp(arr_8))

[[3.16227766 3.46410162 3.60555128 4.        ]
 [4.58257569 4.35889894 3.31662479 3.87298335]]
[[2.30258509 2.48490665 2.56494936 2.77258872]
 [3.04452244 2.94443898 2.39789527 2.7080502 ]]
[[2.20264658e+04 1.62754791e+05 4.42413392e+05 8.88611052e+06]
 [1.31881573e+09 1.78482301e+08 5.98741417e+04 3.26901737e+06]]


In [ ]:
# statistical methods
print(arr_6.std())
print(arr_6.var())
print(arr_6.mean())
print(arr_6.std())

14.430869689661812
208.25
25.5
14.430869689661812


In [ ]:
np.median(arr_6, axis = 1)

array([ 3.,  8., 13., 18., 23., 28., 33., 38., 43., 48.])

In [ ]:
np.median(arr_6, axis = 0)

array([23.5, 24.5, 25.5, 26.5, 27.5])

#### Indexing & Slicing

In [ ]:
arr_7

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35],
       [36, 37, 38, 39, 40],
       [41, 42, 43, 44, 45],
       [46, 47, 48, 49, 50]])

In [ ]:
# row index & columns index
arr_7[2,2]

13

In [ ]:
arr_7[0]      # returns 0th row

array([1, 2, 3, 4, 5])

In [ ]:
arr_7[:,1]      # returns 1st column values

array([ 2,  7, 12, 17, 22, 27, 32, 37, 42, 47])

In [ ]:
# start index = 1, end index = 3
arr_7[1:4, :]

array([[ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [ ]:
# rows = (1,3), columns = (1,3)
arr_7[1:4, 1:4]

array([[ 7,  8,  9],
       [12, 13, 14],
       [17, 18, 19]])

In [ ]:
arr_7[-1, -1]

50

In [ ]:
# start value : 1, exclude last rows & columns
arr_7[1:-1, 1:-1]

array([[ 7,  8,  9],
       [12, 13, 14],
       [17, 18, 19],
       [22, 23, 24],
       [27, 28, 29],
       [32, 33, 34],
       [37, 38, 39],
       [42, 43, 44]])

#### Pandas
    * Pandas are useful python package, reading various file formats.
    * Data Wrangling/Manipulation format
    * Pandas is good for data analysis and data visualization.
    * DataFrame is 2D dataset respresented as rows and columns in 2D format just like spreadsheet.

In [ ]:
import pandas as pd

In [ ]:
auto_price = pd.read_csv("https://raw.githubusercontent.com/ammishra08/MachineLearning/master/Datasets/Automobile_price_data__Raw_.csv")

In [ ]:
auto_price.head()    # show first five rows of dataframe

symboling normalized-losses         make fuel-type aspiration num-of-doors  \
0          3                 ?  alfa-romero       gas        std          two   
1          3                 ?  alfa-romero       gas        std          two   
2          1                 ?  alfa-romero       gas        std          two   
3          2               164         audi       gas        std         four   
4          2               164         audi       gas        std         four   

    body-style drive-wheels engine-location  wheel-base  ...  engine-size  \
0  convertible          rwd           front        88.6  ...          130   
1  convertible          rwd           front        88.6  ...          130   
2    hatchback          rwd           front        94.5  ...          152   
3        sedan          fwd           front        99.8  ...          109   
4        sedan          4wd           front        99.4  ...          136   

   fuel-system  bore  stroke compression-ratio horsepower  peak-rpm city-mpg  \
0         mpfi  3.47    2.68               9.0        111      5000       21   
1         mpfi  3.47    2.68               9.0        111      5000       21   
2         mpfi  2.68    3.47               9.0        154      5000       19   
3         mpfi  3.19    3.40              10.0        102      5500       24   
4         mpfi  3.19    3.40               8.0        115      5500       18   

  highway-mpg  price  
0          27  13495  
1          27  16500  
2          26  16500  
3          30  13950  
4          22  17450  

[5 rows x 26 columns]

In [ ]:
auto_price.tail()    # show last five rows of dataframe

symboling normalized-losses   make fuel-type aspiration num-of-doors  \
200         -1                95  volvo       gas        std         four   
201         -1                95  volvo       gas      turbo         four   
202         -1                95  volvo       gas        std         four   
203         -1                95  volvo    diesel      turbo         four   
204         -1                95  volvo       gas      turbo         four   

    body-style drive-wheels engine-location  wheel-base  ...  engine-size  \
200      sedan          rwd           front       109.1  ...          141   
201      sedan          rwd           front       109.1  ...          141   
202      sedan          rwd           front       109.1  ...          173   
203      sedan          rwd           front       109.1  ...          145   
204      sedan          rwd           front       109.1  ...          141   

     fuel-system  bore  stroke compression-ratio horsepower  peak-rpm  \
200         mpfi  3.78    3.15               9.5        114      5400   
201         mpfi  3.78    3.15               8.7        160      5300   
202         mpfi  3.58    2.87               8.8        134      5500   
203          idi  3.01    3.40              23.0        106      4800   
204         mpfi  3.78    3.15               9.5        114      5400   

    city-mpg highway-mpg  price  
200       23          28  16845  
201       19          25  19045  
202       18          23  21485  
203       26          27  22470  
204       19          25  22625  

[5 rows x 26 columns]

In [ ]:
auto_price.shape    # shape (rows, columns)

(205, 26)

In [ ]:
auto_price.columns     # returns list of columns

Index(['symboling', 'normalized-losses', 'make', 'fuel-type', 'aspiration',
       'num-of-doors', 'body-style', 'drive-wheels', 'engine-location',
       'wheel-base', 'length', 'width', 'height', 'curb-weight', 'engine-type',
       'num-of-cylinders', 'engine-size', 'fuel-system', 'bore', 'stroke',
       'compression-ratio', 'horsepower', 'peak-rpm', 'city-mpg',
       'highway-mpg', 'price'],
      dtype='object')

#### Data Manipulation

In [ ]:
auto_price.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 205 entries, 0 to 204
Data columns (total 26 columns):
 #   Column             Non-Null Count  Dtype  
---  ------             --------------  -----  
 0   symboling          205 non-null    int64  
 1   normalized-losses  205 non-null    object 
 2   make               205 non-null    object 
 3   fuel-type          205 non-null    object 
 4   aspiration         205 non-null    object 
 5   num-of-doors       205 non-null    object 
 6   body-style         205 non-null    object 
 7   drive-wheels       205 non-null    object 
 8   engine-location    205 non-null    object 
 9   wheel-base         205 non-null    float64
 10  length             205 non-null    float64
 11  width              205 non-null    float64
 12  height             205 non-null    float64
 13  curb-weight        205 non-null    int64  
 14  engine-type        205 non-null    object 
 15  num-of-cylinders   205 non-null    object 
 16  engine-size        205 non

In [ ]:
# replace '?' by NaN
auto_price.replace('?', np.nan, inplace = True)

In [ ]:
auto_price.isnull().sum()   # count of missing values for each column

symboling             0
normalized-losses    41
make                  0
fuel-type             0
aspiration            0
num-of-doors          2
body-style            0
drive-wheels          0
engine-location       0
wheel-base            0
length                0
width                 0
height                0
curb-weight           0
engine-type           0
num-of-cylinders      0
engine-size           0
fuel-system           0
bore                  4
stroke                4
compression-ratio     0
horsepower            2
peak-rpm              2
city-mpg              0
highway-mpg           0
price                 4
dtype: int64

#### Slicing & Indexing DataFrame

In [ ]:
# loc = slicing rows & columns by label names
auto_price.loc[:, :]

symboling normalized-losses         make fuel-type aspiration  \
0            3               NaN  alfa-romero       gas        std   
1            3               NaN  alfa-romero       gas        std   
2            1               NaN  alfa-romero       gas        std   
3            2               164         audi       gas        std   
4            2               164         audi       gas        std   
..         ...               ...          ...       ...        ...   
200         -1                95        volvo       gas        std   
201         -1                95        volvo       gas      turbo   
202         -1                95        volvo       gas        std   
203         -1                95        volvo    diesel      turbo   
204         -1                95        volvo       gas      turbo   

    num-of-doors   body-style drive-wheels engine-location  wheel-base  ...  \
0            two  convertible          rwd           front        88.6  ...   
1            two  convertible          rwd           front        88.6  ...   
2            two    hatchback          rwd           front        94.5  ...   
3           four        sedan          fwd           front        99.8  ...   
4           four        sedan          4wd           front        99.4  ...   
..           ...          ...          ...             ...         ...  ...   
200         four        sedan          rwd           front       109.1  ...   
201         four        sedan          rwd           front       109.1  ...   
202         four        sedan          rwd           front       109.1  ...   
203         four        sedan          rwd           front       109.1  ...   
204         four        sedan          rwd           front       109.1  ...   

     engine-size  fuel-system  bore  stroke compression-ratio horsepower  \
0            130         mpfi  3.47    2.68               9.0        111   
1            130         mpfi  3.47    2.68               9.0        111   
2            152         mpfi  2.68    3.47               9.0        154   
3            109         mpfi  3.19    3.40              10.0        102   
4            136         mpfi  3.19    3.40               8.0        115   
..           ...          ...   ...     ...               ...        ...   
200          141         mpfi  3.78    3.15               9.5        114   
201          141         mpfi  3.78    3.15               8.7        160   
202          173         mpfi  3.58    2.87               8.8        134   
203          145          idi  3.01    3.40              23.0        106   
204          141         mpfi  3.78    3.15               9.5        114   

     peak-rpm city-mpg highway-mpg  price  
0        5000       21          27  13495  
1        5000       21          27  16500  
2        5000       19          26  16500  
3        5500       24          30  13950  
4        5500       18          22  17450  
..        ...      ...         ...    ...  
200      5400       23          28  16845  
201      5300       19          25  19045  
202      5500       18          23  21485  
203      4800       26          27  22470  
204      5400       19          25  22625  

[205 rows x 26 columns]

In [ ]:
# loc : slicing rows start index = 1, end index = 7
auto_price.loc[1:8, :]

symboling normalized-losses         make fuel-type aspiration num-of-doors  \
1          3               NaN  alfa-romero       gas        std          two   
2          1               NaN  alfa-romero       gas        std          two   
3          2               164         audi       gas        std         four   
4          2               164         audi       gas        std         four   
5          2               NaN         audi       gas        std          two   
6          1               158         audi       gas        std         four   
7          1               NaN         audi       gas        std         four   
8          1               158         audi       gas      turbo         four   

    body-style drive-wheels engine-location  wheel-base  ...  engine-size  \
1  convertible          rwd           front        88.6  ...          130   
2    hatchback          rwd           front        94.5  ...          152   
3        sedan          fwd           front        99.8  ...          109   
4        sedan          4wd           front        99.4  ...          136   
5        sedan          fwd           front        99.8  ...          136   
6        sedan          fwd           front       105.8  ...          136   
7        wagon          fwd           front       105.8  ...          136   
8        sedan          fwd           front       105.8  ...          131   

   fuel-system  bore  stroke compression-ratio horsepower  peak-rpm city-mpg  \
1         mpfi  3.47    2.68               9.0        111      5000       21   
2         mpfi  2.68    3.47               9.0        154      5000       19   
3         mpfi  3.19    3.40              10.0        102      5500       24   
4         mpfi  3.19    3.40               8.0        115      5500       18   
5         mpfi  3.19    3.40               8.5        110      5500       19   
6         mpfi  3.19    3.40               8.5        110      5500       19   
7         mpfi  3.19    3.40               8.5        110      5500       19   
8         mpfi  3.13    3.40               8.3        140      5500       17   

  highway-mpg  price  
1          27  16500  
2          26  16500  
3          30  13950  
4          22  17450  
5          25  15250  
6          25  17710  
7          25  18920  
8          20  23875  

[8 rows x 26 columns]

In [ ]:
# loc : slice rows and columns by label names
# column labels : start = 'make', end index : 'engine-type'
auto_price.loc[:, 'make':'engine-type']

make fuel-type aspiration num-of-doors   body-style drive-wheels  \
0    alfa-romero       gas        std          two  convertible          rwd   
1    alfa-romero       gas        std          two  convertible          rwd   
2    alfa-romero       gas        std          two    hatchback          rwd   
3           audi       gas        std         four        sedan          fwd   
4           audi       gas        std         four        sedan          4wd   
..           ...       ...        ...          ...          ...          ...   
200        volvo       gas        std         four        sedan          rwd   
201        volvo       gas      turbo         four        sedan          rwd   
202        volvo       gas        std         four        sedan          rwd   
203        volvo    diesel      turbo         four        sedan          rwd   
204        volvo       gas      turbo         four        sedan          rwd   

    engine-location  wheel-base  length  width  height  curb-weight  \
0             front        88.6   168.8   64.1    48.8         2548   
1             front        88.6   168.8   64.1    48.8         2548   
2             front        94.5   171.2   65.5    52.4         2823   
3             front        99.8   176.6   66.2    54.3         2337   
4             front        99.4   176.6   66.4    54.3         2824   
..              ...         ...     ...    ...     ...          ...   
200           front       109.1   188.8   68.9    55.5         2952   
201           front       109.1   188.8   68.8    55.5         3049   
202           front       109.1   188.8   68.9    55.5         3012   
203           front       109.1   188.8   68.9    55.5         3217   
204           front       109.1   188.8   68.9    55.5         3062   

    engine-type  
0          dohc  
1          dohc  
2          ohcv  
3           ohc  
4           ohc  
..          ...  
200         ohc  
201         ohc  
202        ohcv  
203         ohc  
204         ohc  

[205 rows x 13 columns]

In [ ]:
# loc[list of rows, list of columns]
auto_price.loc[[2,4,6,8,10,12,14,16], ['make','fuel-type','num-of-doors','body-style','engine-size','price']]

make fuel-type num-of-doors body-style  engine-size  price
2   alfa-romero       gas          two  hatchback          152  16500
4          audi       gas         four      sedan          136  17450
6          audi       gas         four      sedan          136  17710
8          audi       gas         four      sedan          131  23875
10          bmw       gas          two      sedan          108  16430
12          bmw       gas          two      sedan          164  20970
14          bmw       gas         four      sedan          164  24565
16          bmw       gas          two      sedan          209  41315

In [ ]:
# iloc = index location, slicing by index
auto_price.iloc[1:10, :]

symboling normalized-losses         make fuel-type aspiration num-of-doors  \
1          3               NaN  alfa-romero       gas        std          two   
2          1               NaN  alfa-romero       gas        std          two   
3          2               164         audi       gas        std         four   
4          2               164         audi       gas        std         four   
5          2               NaN         audi       gas        std          two   
6          1               158         audi       gas        std         four   
7          1               NaN         audi       gas        std         four   
8          1               158         audi       gas      turbo         four   
9          0               NaN         audi       gas      turbo          two   

    body-style drive-wheels engine-location  wheel-base  ...  engine-size  \
1  convertible          rwd           front        88.6  ...          130   
2    hatchback          rwd           front        94.5  ...          152   
3        sedan          fwd           front        99.8  ...          109   
4        sedan          4wd           front        99.4  ...          136   
5        sedan          fwd           front        99.8  ...          136   
6        sedan          fwd           front       105.8  ...          136   
7        wagon          fwd           front       105.8  ...          136   
8        sedan          fwd           front       105.8  ...          131   
9    hatchback          4wd           front        99.5  ...          131   

   fuel-system  bore  stroke compression-ratio horsepower  peak-rpm city-mpg  \
1         mpfi  3.47    2.68               9.0        111      5000       21   
2         mpfi  2.68    3.47               9.0        154      5000       19   
3         mpfi  3.19    3.40              10.0        102      5500       24   
4         mpfi  3.19    3.40               8.0        115      5500       18   
5         mpfi  3.19    3.40               8.5        110      5500       19   
6         mpfi  3.19    3.40               8.5        110      5500       19   
7         mpfi  3.19    3.40               8.5        110      5500       19   
8         mpfi  3.13    3.40               8.3        140      5500       17   
9         mpfi  3.13    3.40               7.0        160      5500       16   

  highway-mpg  price  
1          27  16500  
2          26  16500  
3          30  13950  
4          22  17450  
5          25  15250  
6          25  17710  
7          25  18920  
8          20  23875  
9          22    NaN  

[9 rows x 26 columns]

In [ ]:
# iloc = index location, slicing by index
auto_price.iloc[1:10, 2:11]

make fuel-type aspiration num-of-doors   body-style drive-wheels  \
1  alfa-romero       gas        std          two  convertible          rwd   
2  alfa-romero       gas        std          two    hatchback          rwd   
3         audi       gas        std         four        sedan          fwd   
4         audi       gas        std         four        sedan          4wd   
5         audi       gas        std          two        sedan          fwd   
6         audi       gas        std         four        sedan          fwd   
7         audi       gas        std         four        wagon          fwd   
8         audi       gas      turbo         four        sedan          fwd   
9         audi       gas      turbo          two    hatchback          4wd   

  engine-location  wheel-base  length  
1           front        88.6   168.8  
2           front        94.5   171.2  
3           front        99.8   176.6  
4           front        99.4   176.6  
5           front        99.8   177.3  
6           front       105.8   192.7  
7           front       105.8   192.7  
8           front       105.8   192.7  
9           front        99.5   178.2

#### Select Columns

In [ ]:
auto_price['price']    # select column by column names

0      13495
1      16500
2      16500
3      13950
4      17450
       ...  
200    16845
201    19045
202    21485
203    22470
204    22625
Name: price, Length: 205, dtype: object

In [ ]:
auto_price[['make','body-style','fuel-type','price']]    # select multiple columns by individual columnn names

make   body-style fuel-type  price
0    alfa-romero  convertible       gas  13495
1    alfa-romero  convertible       gas  16500
2    alfa-romero    hatchback       gas  16500
3           audi        sedan       gas  13950
4           audi        sedan       gas  17450
..           ...          ...       ...    ...
200        volvo        sedan       gas  16845
201        volvo        sedan       gas  19045
202        volvo        sedan       gas  21485
203        volvo        sedan    diesel  22470
204        volvo        sedan       gas  22625

[205 rows x 4 columns]

#### Filter
    * To filter rows by boolean condition

In [ ]:
auto_price['make'] == 'audi'

0      False
1      False
2      False
3       True
4       True
       ...  
200    False
201    False
202    False
203    False
204    False
Name: make, Length: 205, dtype: bool

In [ ]:
auto_price[auto_price['make'] == 'audi']

symboling normalized-losses  make fuel-type aspiration num-of-doors  \
3          2               164  audi       gas        std         four   
4          2               164  audi       gas        std         four   
5          2               NaN  audi       gas        std          two   
6          1               158  audi       gas        std         four   
7          1               NaN  audi       gas        std         four   
8          1               158  audi       gas      turbo         four   
9          0               NaN  audi       gas      turbo          two   

  body-style drive-wheels engine-location  wheel-base  ...  engine-size  \
3      sedan          fwd           front        99.8  ...          109   
4      sedan          4wd           front        99.4  ...          136   
5      sedan          fwd           front        99.8  ...          136   
6      sedan          fwd           front       105.8  ...          136   
7      wagon          fwd           front       105.8  ...          136   
8      sedan          fwd           front       105.8  ...          131   
9  hatchback          4wd           front        99.5  ...          131   

   fuel-system  bore  stroke compression-ratio horsepower  peak-rpm city-mpg  \
3         mpfi  3.19    3.40              10.0        102      5500       24   
4         mpfi  3.19    3.40               8.0        115      5500       18   
5         mpfi  3.19    3.40               8.5        110      5500       19   
6         mpfi  3.19    3.40               8.5        110      5500       19   
7         mpfi  3.19    3.40               8.5        110      5500       19   
8         mpfi  3.13    3.40               8.3        140      5500       17   
9         mpfi  3.13    3.40               7.0        160      5500       16   

  highway-mpg  price  
3          30  13950  
4          22  17450  
5          25  15250  
6          25  17710  
7          25  18920  
8          20  23875  
9          22    NaN  

[7 rows x 26 columns]

In [ ]:
auto_price[auto_price['highway-mpg'] >= 45]

symboling normalized-losses        make fuel-type aspiration  \
18           2               121   chevrolet       gas        std   
30           2               137       honda       gas        std   
90           1               128      nissan    diesel        std   
159          0                91      toyota    diesel        std   
160          0                91      toyota       gas        std   
182          2               122  volkswagen    diesel        std   
184          2                94  volkswagen    diesel        std   

    num-of-doors body-style drive-wheels engine-location  wheel-base  ...  \
18           two  hatchback          fwd           front        88.4  ...   
30           two  hatchback          fwd           front        86.6  ...   
90           two      sedan          fwd           front        94.5  ...   
159         four  hatchback          fwd           front        95.7  ...   
160         four      sedan          fwd           front        95.7  ...   
182          two      sedan          fwd           front        97.3  ...   
184         four      sedan          fwd           front        97.3  ...   

     engine-size  fuel-system  bore  stroke compression-ratio horsepower  \
18            61         2bbl  2.91    3.03               9.5         48   
30            92         1bbl  2.91    3.41               9.6         58   
90           103          idi  2.99    3.47              21.9         55   
159          110          idi  3.27    3.35              22.5         56   
160           98         2bbl  3.19    3.03               9.0         70   
182           97          idi  3.01    3.40              23.0         52   
184           97          idi  3.01    3.40              23.0         52   

     peak-rpm city-mpg highway-mpg price  
18       5100       47          53  5151  
30       4800       49          54  6479  
90       4800       45          50  7099  
159      4500       38          47  7788  
160      4800       38          47  7738  
182      4800       37          46  7775  
184      4800       37          46  7995  

[7 rows x 26 columns]

In [ ]:
auto_price[(auto_price['highway-mpg'] >= 40) & (auto_price['body-style'] == 'sedan')]

symboling normalized-losses        make fuel-type aspiration  \
20           0                81   chevrolet       gas        std   
44           1               NaN       isuzu       gas        std   
45           0               NaN       isuzu       gas        std   
63           0               NaN       mazda    diesel        std   
90           1               128      nissan    diesel        std   
160          0                91      toyota       gas        std   
182          2               122  volkswagen    diesel        std   
184          2                94  volkswagen    diesel        std   
187          2                94  volkswagen    diesel      turbo   

    num-of-doors body-style drive-wheels engine-location  wheel-base  ...  \
20          four      sedan          fwd           front        94.5  ...   
44           two      sedan          fwd           front        94.5  ...   
45          four      sedan          fwd           front        94.5  ...   
63           NaN      sedan          fwd           front        98.8  ...   
90           two      sedan          fwd           front        94.5  ...   
160         four      sedan          fwd           front        95.7  ...   
182          two      sedan          fwd           front        97.3  ...   
184         four      sedan          fwd           front        97.3  ...   
187         four      sedan          fwd           front        97.3  ...   

     engine-size  fuel-system  bore  stroke compression-ratio horsepower  \
20            90         2bbl  3.03    3.11               9.6         70   
44            90         2bbl  3.03    3.11               9.6         70   
45            90         2bbl  3.03    3.11               9.6         70   
63           122          idi  3.39    3.39              22.7         64   
90           103          idi  2.99    3.47              21.9         55   
160           98         2bbl  3.19    3.03               9.0         70   
182           97          idi  3.01    3.40              23.0         52   
184           97          idi  3.01    3.40              23.0         52   
187           97          idi  3.01    3.40              23.0         68   

     peak-rpm city-mpg highway-mpg  price  
20       5400       38          43   6575  
44       5400       38          43    NaN  
45       5400       38          43    NaN  
63       4650       36          42  10795  
90       4800       45          50   7099  
160      4800       38          47   7738  
182      4800       37          46   7775  
184      4800       37          46   7995  
187      4500       37          42   9495  

[9 rows x 26 columns]

In [ ]:
# Display distinct or unique values. (Apply it on categorical columns)
auto_price['make'].unique()

array(['alfa-romero', 'audi', 'bmw', 'chevrolet', 'dodge', 'honda',
       'isuzu', 'jaguar', 'mazda', 'mercedes-benz', 'mercury',
       'mitsubishi', 'nissan', 'peugot', 'plymouth', 'porsche', 'renault',
       'saab', 'subaru', 'toyota', 'volkswagen', 'volvo'], dtype=object)

In [ ]:
auto_price['make'].value_counts()     # Frequency of Categorical Column

make
toyota           32
nissan           18
mazda            17
mitsubishi       13
honda            13
volkswagen       12
subaru           12
peugot           11
volvo            11
dodge             9
mercedes-benz     8
bmw               8
audi              7
plymouth          7
saab              6
porsche           5
isuzu             4
jaguar            3
chevrolet         3
alfa-romero       3
renault           2
mercury           1
Name: count, dtype: int64

#### Drop()
    * Dropping Rows & Columns

In [ ]:
# Drops columns by using indexes
auto_price.drop(['symboling','normalized-losses'], axis = 1, inplace = True)

In [ ]:
auto_price.head()

In [ ]:
# Drops rows by using indexes
auto_price.drop([0, 1, 2, 3, 4, 5, 6, 7, 8], axis = 0)

make fuel-type aspiration num-of-doors body-style drive-wheels  \
9     audi       gas      turbo          two  hatchback          4wd   
10     bmw       gas        std          two      sedan          rwd   
11     bmw       gas        std         four      sedan          rwd   
12     bmw       gas        std          two      sedan          rwd   
13     bmw       gas        std         four      sedan          rwd   
..     ...       ...        ...          ...        ...          ...   
200  volvo       gas        std         four      sedan          rwd   
201  volvo       gas      turbo         four      sedan          rwd   
202  volvo       gas        std         four      sedan          rwd   
203  volvo    diesel      turbo         four      sedan          rwd   
204  volvo       gas      turbo         four      sedan          rwd   

    engine-location  wheel-base  length  width  ...  engine-size  fuel-system  \
9             front        99.5   178.2   67.9  ...          131         mpfi   
10            front       101.2   176.8   64.8  ...          108         mpfi   
11            front       101.2   176.8   64.8  ...          108         mpfi   
12            front       101.2   176.8   64.8  ...          164         mpfi   
13            front       101.2   176.8   64.8  ...          164         mpfi   
..              ...         ...     ...    ...  ...          ...          ...   
200           front       109.1   188.8   68.9  ...          141         mpfi   
201           front       109.1   188.8   68.8  ...          141         mpfi   
202           front       109.1   188.8   68.9  ...          173         mpfi   
203           front       109.1   188.8   68.9  ...          145          idi   
204           front       109.1   188.8   68.9  ...          141         mpfi   

     bore stroke  compression-ratio horsepower peak-rpm city-mpg  highway-mpg  \
9    3.13   3.40                7.0        160     5500       16           22   
10   3.50   2.80                8.8        101     5800       23           29   
11   3.50   2.80                8.8        101     5800       23           29   
12   3.31   3.19                9.0        121     4250       21           28   
13   3.31   3.19                9.0        121     4250       21           28   
..    ...    ...                ...        ...      ...      ...          ...   
200  3.78   3.15                9.5        114     5400       23           28   
201  3.78   3.15                8.7        160     5300       19           25   
202  3.58   2.87                8.8        134     5500       18           23   
203  3.01   3.40               23.0        106     4800       26           27   
204  3.78   3.15                9.5        114     5400       19           25   

     price  
9      NaN  
10   16430  
11   16925  
12   20970  
13   21105  
..     ...  
200  16845  
201  19045  
202  21485  
203  22470  
204  22625  

[196 rows x 24 columns]

#### Statistical Methods

In [ ]:
# Typecasting string to float data type
auto_price['price'] = auto_price['price'].astype('float')

In [ ]:
auto_price['horsepower'] = auto_price['horsepower'].astype('float')

In [ ]:
np.round(auto_price['price'].mean())

13207.0

In [ ]:
auto_price['price'].median()

10295.0

In [ ]:
auto_price['make'].mode()    # most-frequent value

0    toyota
Name: make, dtype: object

#### Handling Missing Values.
    * fillna()
    * replace()
    * dropna()

In [ ]:
auto_price.isnull().sum()

make                 0
fuel-type            0
aspiration           0
num-of-doors         2
body-style           0
drive-wheels         0
engine-location      0
wheel-base           0
length               0
width                0
height               0
curb-weight          0
engine-type          0
num-of-cylinders     0
engine-size          0
fuel-system          0
bore                 4
stroke               4
compression-ratio    0
horsepower           2
peak-rpm             2
city-mpg             0
highway-mpg          0
price                4
dtype: int64

In [ ]:
auto_price['price'].fillna(np.round(auto_price['price'].mean()), inplace = True)

In [ ]:
auto_price.dropna(inplace = True)